export const ORIGIN_SELECTED = "ORIGIN_SELECTED";
export const DESTINATION_SELECTED = "DESTINATION_SELECTED";
export const DIRECTION_CREATED = "DIRECTION_CREATED"
export const BOOKING_TYPE_CHANGED = "BOOKING_TYPE_CHANGED"
export const DATE_ADDED = "DATE_ADDED";
export const TIME_ADDED="TIME_ADDED";


export const VEHICLES_ADDED = "VEHICLES_ADDED";
export const VEHICLES_LOADING = "VEHICLES_LOADING";


export const VEHICLE_SELECTED="VEHICLE_SELECTED";

export const PACKAGE_SELECTED = "PACKAGE_SELECTED";

export const JOURNEY_TYPE_CHANGED="JOURNEY_TYPE_CHANGED";
export const JOURNEY_DATE_CHANGED="JOURNEY_DATE_CHANGED";
export const JOURNEY_TIME_CHANGED="JOURNEY_TIME_CHANGED";

export const DELIVERY_TYPE_CHANGED="DELIVERY_TYPE_CHANGED";
export const DELIVERY_IMAGES_ADDED="DELIVERY_IMAGES_ADDED";
export const DELIVERY_COMMENT_CHANGED="JOURNEY_TIME_CHANGED";

export const CITIES_ADDED="CITIES_ADDED";

export const PAYMENT_METHOD_CHANGED="PAYMENT_METHOD_CHANGED";
export const COUPON_ADDED="COUPON_ADDED";
export const NOTE_ADDED="NOTE_ADDED";

export const REQUEST_CONFIRMED="REQUEST_CONFIRMED";
export const DRIVER_ASSIGNED="DRIVER_ASSIGNED";

export const REQUEST_CANCELED="REQUEST_CANCELED";
export const TERMINATION_REASON_ADDED="TERMINATION_REASON_ADDED";


export const STEP_CHANGED = "STEP_CHANGED";

export const INPUT_VALIDATED = "INPUT_VALIDATED";