export const ORIGIN_SELECTED = "ORIGIN_SELECTED";
export const DESTINATION_SELECTED = "DESTINATION_SELECTED";
export const DIRECTION_CREATED = "DIRECTION_CREATED";
export const BOOKING_TYPE_CHANGED = "BOOKING_TYPE_CHANGED";
export const DATE_ADDED = "DATE_ADDED";
export const TIME_ADDED = "TIME_ADDED";

export const VEHICLES_ADDED = "VEHICLES_ADDED";
export const VEHICLES_LOADING = "VEHICLES_LOADING";

export const VEHICLE_SELECTED = "VEHICLE_SELECTED";

export const PACKAGE_SELECTED = "PACKAGE_SELECTED";

export const JOURNEY_TYPE_CHANGED = "JOURNEY_TYPE_CHANGED";
export const JOURNEY_DATE_CHANGED = "JOURNEY_DATE_CHANGED";
export const JOURNEY_TIME_CHANGED = "JOURNEY_TIME_CHANGED";

export const DELIVERY_IMAGES_UPLOADED = "DELIVERY_IMAGES_UPLOADED";
export const DELIVERY_IMAGES_ADDED = "DELIVERY_IMAGES_ADDED";
export const DELIVERY_IMAGE_REMOVED = "DELIVERY_IMAGES_REMOVED";
export const DELIVERY_COMMENT_CHANGED = "DELIVERY_COMMENT_CHANGED";

export const CITIES_ADDED = "CITIES_ADDED";

export const PAYMENT_METHOD_CHANGED = "PAYMENT_METHOD_CHANGED";
export const COUPON_ADDED = "COUPON_ADDED";
export const NOTE_ADDED = "NOTE_ADDED";

export const HOUSE_NUMBER_ADDED = "HOUSE_NUMBER_ADDED";
export const LANDMARK_ADDED = "LANDMARK_ADDED";
export const VALIDATED_ADDRESS = "VALIDATED_ADDRESS";
export const DELIVERY_SELECTED = "DELIVERY_SELECTED";

export const REQUEST_CONFIRMED = "REQUEST_CONFIRMED";
export const DRIVER_ASSIGNED = "DRIVER_ASSIGNED";

export const REQUEST_CANCELED = "REQUEST_CANCELED";
export const TERMINATION_REASON_ADDED = "TERMINATION_REASON_ADDED";

export const STEP_CHANGED = "STEP_CHANGED";

export const PAYMENT_METHODS_FETCHED = "PAYMENT_METHODS_FETCHED";
export const FETCH_PAYMENT_METHOD_CALLED = "FETCH_PAYMENT_METHOD_CALLED";

export const AVAILABLE_VEHICLES_ADDED = "AVAILABLE_VEHICLES_ADDED";
export const AVAILABLE_VEHICLES_LOADING = "AVAILABLE_VEHICLES_LOADING";

export const PAYMENT_LOADING_STATE_CHANGED = "PAYMENT_LOADING_STATE_CHANGED";
export const INPUT_VALIDATED = "INPUT_VALIDATED";


export const FETCH_FARE_ESTIMATE_INITIATED = "FETCH_FARE_ESTIMATE_INITIATED";
export const FARE_ESTIMATE_FETCHED = "FARE_ESTIMATE_FETCHED";
export const FARE_LOADING_STATE_CHANGED = "FARE_LOADING_STATE_CHANGED";
