variables:
  CI_REGISTRY_IMAGE: "docker.elnetech.com/elnet/taxiye/frontend/public-web" 
  DOCKER_TLS_CERTDIR: ""
docker-build:
  # Official docker image.
  image: docker:19.03.12
  stage: build 
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:develop-$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:develop-latest .
    - docker push $CI_REGISTRY_IMAGE:develop-latest
    - docker push $CI_REGISTRY_IMAGE:develop-$CI_COMMIT_SHORT_SHA
  only:
    - develop
