export const ORIGIN_SELECTED = "ORIGIN_SELECTED";
export const DESTINATION_SELECTED = "DESTINATION_SELECTED";
export const DIRECTION_CREATED = "DIRECTION_CREATED"
export const DATE_ADDED = "";
export const TIME_ADDED="";