export const FULL_NAME_ADDED = "ADMIN_FULL_NAME_ADDED";
export const EMAIL_ADDED = "ADMIN_EMAIL_ADDED";
export const PHONE_NUMBER_ADDED = "ADMIN_PHONE_NUMBER_ADDED";
export const PHONE_NUMBER_BEFORE_VALIDATION_ADDED = "PHONE_NUMBER_BEFORE_VALIDATION_ADDED";
export const VALIDATED_ACCOUNT_INFORMATION = "VALIDATED_ACCOUNT_INFORMATION";
export const PROFILE_CHANGED = "PROFILE_CHANGED";


export const COMPANY_NAME_ADDED = "COMPANY_NAME_ADDED";
export const DEBIT_LIMIT_ADDED = "COMPANY_DEBIT_LIMIT_ADDED";
export const ADDRESS_ADDED = "COMPANY_ADDRESS_ADDED";
export const MAX_USER_ADDED = "COMPANY_MAX_USER_ADDED";
export const OFFICIAL_EMAIL_ADDED = "COMPANY_OFFICIAL_EMAIL_ADDED";
export const VAT_NUMBER_ADDED = "COMPANY_VAT_NUMBER_ADDED";
export const COMPANY_PHONE_NUMBER_ADDED = "COMPANY_PHONE_NUMBER_ADDED";
export const COMPANY_INVOICE_EMAIL_ADDED = "COMPANY_INVOICE_EMAIL_ADDED";

export const VALIDATED_COMPANY_INFORMATION = "VALIDATED_COMPANY_INFORMATION";

export const ROLES_TAB_INITIATED = "ROLES_TAB_INITIATED";
export const ROLES_DATA_FETCHED = "ROLES_DATA_FETCHED";
export const ROLES_DATA_QUERY_ADDED = "ROLES_DATA_QUERY_ADDED";
export const ROLES_TAB_LOADING_CHANGED = "ROLES_TAB_LOADING_CHANGED";

export const NEW_FULL_NAME_ADDED = "NEW_FULL_NAME_ADDED";
export const NEW_EMAIL_ADDED = "NEW_EMAIL_ADDED";
export const NEW_ROLE_SELECTED = "NEW_ROLE_SELECTED";
export const SUBMITTING_NEW_ROLE_INITIATED = "SUBMITTING_NEW_ROLE_INITIATED";
export const ROLE_FORM_VALIDATED = "ROLE_FORM_VALIDATED";
export const ROLE_FORM_LOADING_CHANGED = "ROLE_FORM_LOADING_CHANGED";
export const RESET_NEW_FORM = "RESET_NEW_FORM";
export const SAVE_NEW_FORM_INITIATED = "SAVE_NEW_FORM_INITIATED";



export const RESET = "RESET";