export const FULL_NAME_ADDED = "ADMIN_FULL_NAME_ADDED";
export const EMAIL_ADDED = "ADMIN_EMAIL_ADDED";
export const PHONE_NUMBER_ADDED = "ADMIN_PHONE_NUMBER_ADDED";
export const VALIDATED_ACCOUNT_INFORMATION = "VALIDATED_ACCOUNT_INFORMATION";
export const PROFILE_CHANGED = "PROFILE_CHANGED";


export const COMPANY_NAME_ADDED = "COMPANY_NAME_ADDED";
export const DEBIT_LIMIT_ADDED = "COMPANY_DEBIT_LIMIT_ADDED";
export const ADDRESS_ADDED = "COMPANY_ADDRESS_ADDED";
export const MAX_USER_ADDED = "COMPANY_MAX_USER_ADDED";
export const OFFICIAL_EMAIL_ADDED = "COMPANY_OFFICIAL_EMAIL_ADDED";
export const VAT_NUMBER_ADDED = "COMPANY_VAT_NUMBER_ADDED";
export const COMPANY_PHONE_NUMBER_ADDED = "COMPANY_PHONE_NUMBER_ADDED";
export const COMPANY_INVOICE_EMAIL_ADDED = "COMPANY_INVOICE_EMAIL_ADDED";

export const VALIDATED_COMPANY_INFORMATION = "VALIDATED_COMPANY_INFORMATION";


export const RESET = "RESET";