export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";
export const EMPLOYEE_LIST_FETCHED = "EMPLOYEE_LIST_FETCHED";
export const QUERY_ADDED = "QUERY_ADDED";
export const LOADING_INITIATED = "EMPLOYEE_LOADING_INITIATED";
export const SEARCH_LOADING_INITIATED = "SEARCH_LOADING_INITIATED";
export const REQUEST_VALIDATED = "REQUEST_VALIDATED";

export const ORIGIN_SELECTED = "EMPLOYEE_DISPATCH_ORIGIN_SELECTED";
export const DESTINATION_SELECTED = "EMPLOYEE_DISPATCH_DESTINATION_SELECTED";
export const DATE_ADDED = "EMPLOYEE_DISPATCH_DATE_ADDED";
export const TIME_ADDED = "EMPLOYEE_DISPATCH_TIME_ADDED";

export const VEHICLES_ADDED = "EMPLOYEE_VEHICLES_ADDED";
export const VEHICLE_SELECTED = "EMPLOYEE_VEHICLE_SELECTED";

export const GET_EMPLOYEES_INITIATED = "GET_EMPLOYEES_INITIATED";
export const API_QUERY_ADDED = "API_QUERY_ADDED";
export const EMPLOYEE_ROUTE_CHANGED = "EMPLOYEE_ROUTE_CHANGED";

export const EMPLOYEE_FORM_INITIATED = "EMPLOYEE_FORM_INITIATED";
export const EMPLOYEE_APPENDED = "EMPLOYEE_APPENDED";
export const EMPLOYEE_REMOVED = "EMPLOYEE_REMOVED";
export const GROUP_FETCHED = "GROUP_FETCHED";

export const EMPLOYEE_PHONE_ADDED = "EMPLOYEE_PHONE_ADDED";
export const EMPLOYEE_FIRST_NAME_CHANGED = "EMPLOYEE_FIRST_NAME_CHANGED";
export const EMPLOYEE_LAST_NAME_CHANGED = "EMPLOYEE_LAST_NAME_CHANGED";
export const EMPLOYEE_EMAIL_CHANGED = "EMPLOYEE_EMAIL_CHANGED";
export const EMPLOYEE_GROUP_CHANGED = "EMPLOYEE_GROUP_CHANGED";
export const EMPLOYEE_FORM_VALIDATED = "EMPLOYEE_FORM_VALIDATED";
export const RESET_EMPLOYEE_REGISTRATION = "RESET_EMPLOYEE_REGISTRATION";


export const TOGGLE_USER_STATUS_INITIATED = "TOGGLE_USER_STATUS_INITIATED";
export const TOGGLE_USER_STATUS_FINISHED = "TOGGLE_USER_STATUS_FINISHED";



export const RESET = "RESET";
