export const EMPLOYEE_SELECTED = "EMPLOYEE_SELECTED";
export const EMPLOYEE_LIST_FETCHED = "EMPLOYEE_LIST_FETCHED";
export const QUERY_ADDED = "QUERY_ADDED";
export const LOADING_INITIATED = "EMPLOYEE_LOADING_INITIATED";
export const SEARCH_LOADING_INITIATED = "SEARCH_LOADING_INITIATED";
export const REQUEST_VALIDATED = "REQUEST_VALIDATED";

export const ORIGIN_SELECTED = "EMPLOYEE_DISPATCH_ORIGIN_SELECTED";
export const DESTINATION_SELECTED = "EMPLOYEE_DISPATCH_DESTINATION_SELECTED";
export const DATE_ADDED = "EMPLOYEE_DISPATCH_DATE_ADDED";
export const TIME_ADDED = "EMPLOYEE_DISPATCH_TIME_ADDED";

export const VEHICLES_ADDED = "EMPLOYEE_VEHICLES_ADDED";
export const VEHICLE_SELECTED = "EMPLOYEE_VEHICLE_SELECTED";

export const GET_EMPLOYEES_INITIATED = "GET_EMPLOYEES_INITIATED";
export const API_QUERY_ADDED = "API_QUERY_ADDED";


export const RESET = "RESET";
