export const GROUP_ROUTE_CHANGED = "GROUP_ROUTE_CHANGED";

export const FETCH_GROUP_INITIATED = "FETCH_GROUP_INITIATED";
export const GROUP_DATA_FETCHED = "GROUP_DATA_FETCHED";
export const QUERY_ADDED = "QUERY_ADDED";

export const GROUP_NAME_ADDED = "GROUP_NAME_ADDED";
export const MONTHLY_BUDGET_ADDED = "MONTHLY_BUDGET_ADDED";
export const MONTHLY_RIDE_ADDED = "MONTHLY_RIDE_ADDED";
export const PAYMENT_MODE_SELECTED = "PAYMENT_MODE_SELECTED";

export const DAYS_SELECTED = "DAYS_SELECTED";
export const TIME_RANGE_ADDED = "TIME_RANGE_ADDED";
export const VEHICLE_SELECTION_MADE = "VEHICLE_SELECTION_MADE";
export const VEHICLE_REMOVED = "VEHICLE_REMOVED";
export const FORM_VALIDATED = "FORM_VALIDATED";

export const RESET = "RESET";

export const INITIATE_LOADING = "INITIATE_LOADING";
