export const COMPANY_OVERVIEW_PULL_IN_INITIATED = "COMPANY_OVERVIEW_PULL_IN_INITIATED";
export const COMPANY_OVERVIEW_PULLED_IN = "COMPANY_OVERVIEW_PULLED_IN";

export const RECENT_RIDES_PULL_IN_INITIATED = "RECENT_RIDES_PULL_IN_INITIATED";
export const RECENT_RIDES_PULLED_IN = "RECENT_RIDES_PULLED_IN";

export const COMPANY_OVERVIEW_LOADING_CHANGED = "COMPANY_OVERVIEW_LOADING_CHANGED";
export const RECENT_RIDES_LOADING_CHANGED = "RECENT_RIDES_LOADING_CHANGED";