export const COMPANY_NAME_ADDED = "COMPANY_NAME_ADDED";
export const COMPANY_OFFICIAL_EMAIL_ADDED = "COMPANY_OFFICIAL_EMAIL_ADDED";
export const COMPANY_PHONE_NUMBER_ADDED = "COMPANY_PHONE_NUMBER_ADDED";
export const NUMBER_OF_EMPLOYEES_ADDED = "NUMBER_OF_EMPLOYEES_ADDED";
export const COMPANY_INFO_VALIDATED = "COMPANY_INFO_VALIDATED";
export const VALIDATION_UPDATED = "VALIDATION_UPDATED";

export const COMPANY_DATA_SUBMITTED = "COMPANY_DATA_SUBMITTED";
export const COMPANY_DATA_SUBMIT_INITIATED = "COMPANY_DATA_SUBMIT_INITIATED";

export const LOADING_INITIATED = "LOADING_INITIATED";

export const RESET = "RESET";
