export const COMPANY_NAME_ADDED = "COMPANY_NAME_ADDED";
export const COMPANY_OFFICIAL_EMAIL_ADDED = "COMPANY_OFFICIAL_EMAIL_ADDED";
export const COMPANY_PHONE_NUMBER_ADDED = "COMPANY_PHONE_NUMBER_ADDED";
export const NUMBER_OF_EMPLOYEES_ADDED = "NUMBER_OF_EMPLOYEES_ADDED";
export const COMPANY_INFO_VALIDATED = "COMPANY_INFO_VALIDATED";
export const VALIDATION_UPDATED = "VALIDATION_UPDATED";

export const COMPANY_DATA_SUBMITTED = "COMPANY_DATA_SUBMITTED";
export const COMPANY_DATA_SUBMIT_INITIATED = "COMPANY_DATA_SUBMIT_INITIATED";

export const LOADING_INITIATED = "LOADING_INITIATED";

export const STEP_CHANGED = "STEP_CHANGED";

export const CORPORATE_OTP_ADDED = "CORPORATE_OTP_ADDED";

export const CORPORATE_OTP_SENT = "CORPORATE_OTP_SENT";
export const CORPORATE_OTP_SUBMITTED = "CORPORATE_OTP_SUBMITTED";
export const CORPORATE_OTP_RESENT = "CORPORATE_OTP_RESENT";

export const ADMIN_NAME_ADDED = "ADMIN_NAME_ADDED";
export const ADMIN_EMAIL_ADDED = "ADMIN_EMAIL_ADDED";
export const ADMIN_PASSWORD_ADDED = "ADMIN_PASSWORD_ADDED";
export const ADMIN_CONFIRMATION_PASSWORD_ADDED =
  "ADMIN_CONFIRMATION_PASSWORD_ADDED";
export const ADMIN_VALIDATION_UPDATED = "ADMIN_VALIDATION_UPDATED";

export const ADMIN_DATA_SUBMITTED = "ADMIN_DATA_SUBMITTED";
export const ADMIN_DATA_SUBMIT_INITIATED = "ADMIN_DATA_SUBMIT_INITIATED";
export const CORPORATE_TERMS_CHANGED = "CORPORATE_TERMS_CHANGED";

export const RESET = "RESET";
