export const FETCH_REQUESTS_INITIATED = "FETCH_REQUESTS_INITIATED";
export const REQUESTS_DATA_FETCHED = "REQUESTS_DATA_FETCHED";
export const REQUESTS_QUERY_ADDED = "REQUESTS_QUERY_ADDED";

export const DEBIT_LIMIT_ADDED = "DEBIT_LIMIT_ADDED";
export const USER_LIMIT_ADDED = "USER_LIMIT_ADDED";
export const REASON_ADDED = "REASON_ADDED";
export const FORM_VALIDATED = "FORM_VALIDATED";

export const INITIATE_FORM_SUBMISSION = "INITIATE_FORM_SUBMISSION";
export const FORM_DATA_SUBMITTED = "FORM_DATA_SUBMITTED";
export const CANCEL_REQUEST_INITIATED = "CANCEL_REQUEST_INITIATED";


export const LOADING_INITIATED = "LOADING_INITIATED";