export const FETCH_REQUESTS_INITIATED = "FETCH_REQUESTS_INITIATED";
export const REQUESTS_DATA_FETCHED = "REQUESTS_DATA_FETCHED";
export const REQUESTS_QUERY_ADDED = "REQUESTS_QUERY_ADDED";

export const DEBIT_LIMIT_ADDED = "DEBIT_LIMIT_ADDED";
export const USER_LIMIT_ADDED = "USER_LIMIT_ADDED";
export const REASON_ADDED = "REASON_ADDED";
export const FORM_VALIDATED = "FORM_VALIDATED";


export const LOADING_INITIATED = "LOADING_INITIATED";