export const FETCH_REQUESTS_INITIATED = "FETCH_REQUESTS_INITIATED";
export const REQUESTS_DATA_FETCHED = "REQUESTS_DATA_FETCHED";
export const REQUESTS_QUERY_ADDED = "REQUESTS_QUERY_ADDED";

export const LOADING_INITIATED = "LOADING_INITIATED";