export const DATE_CHANGED = "DATE_CHANGED";
export const CITY_CHANGED = "CITY_CHANGED";
export const QUERY_CHANGED = "QUERY_CHANGED";
export const FETCH_RIDES_INITIATED = "FETCH_RIDES_INITIATED";
export const RIDES_FETCHED = "RIDES_FETCHED";
export const LOADING_INITIATED = "LOADING_INITIATED";

export const TYPE_CHANGED = "TYPE_CHANGED";
export const RESET= "RESET";

  