export const DRIVER_FULLNAME_ADDED = "DRIVER_FULLNAME_ADDED";
export const DRIVER_GENDER_ADDED = "DRIVER_GENDER_ADDED";
export const DRIVER_COUNTRY_ADDED = "DRIVER_COUNTRY_ADDED";

export const PHONE_ADDED = "DRIVER_PHONE_ADDED";
export const PHONE_SUBMITTED = "DRIVER_PHONE_SUBMITTED";

export const OTP_ADDED = "DRIVER_OTP_ADDED";
export const DRIVER_INFO_SUBMISSION_INITIATED = "DRIVER_INFO_SUBMISSION_INITIATED";

export const STEP_CHANGED = "DRIVER_STEP_CHANGED";
export const SUB_STEP_CHANGED = "SUB_STEP_CHANGED";

export const TERMS_CHANGED = "DRIVER_TERMS_CHANGED";
export const FIRST_FORM_VALIDATED = "FIRST_FORM_VALIDATED";

export const OTP_SENT = "DRIVER_OTP_SENT";
export const OTP_SUBMITTED = "DRIVER_OTP_SUBMITTED";
export const DRIVER_OTP_VALIDATED = "DRIVER_OTP_VALIDATED";

export const OTP_RESENT = "DRIVER_OTP_RESENT";
export const LOADING_UPDATED = "DRIVER_LOADING_UPDATED";

export const VEHICLE_CHANGED = "DRIVER_VEHICLE_CHANGED";

export const INITIATE_SUBMIT_DRIVER_FORM = "INITIATE_SUBMIT_DRIVER_FORM";
export const DRIVER_FORM_SUBMITTED = "DRIVER_FORM_SUBMITTED";

export const PROGRESS_CHANGED = "PROGRESS_CHANGED";

export const PORTRAIT_IMAGE_ADDED = "PORTRAIT_IMAGE_ADDED";
export const PORTRAIT_IMAGE_DELETED = "PORTRAIT_IMAGE_DELETED";
export const UPLOAD_PORTRAITE_IMAGE_INITIATED =
  "UPLOAD_PORTRAITE_IMAGE_INITIATED";
export const PORTRAIT_IMAGE_UPLOADED = "PORTRAIT_IMAGE_UPLOADED";

export const DRIVER_LICENSE_IMAGE_ADDED = "DRIVER_LICENSE_IMAGE_ADDED";
export const DRIVER_LICENSE_IMAGE_DELETED = "DRIVER_LICENSE_IMAGE_DELETED";
export const UPLOAD_DRIVER_LICENSE_IMAGE_INITIATED =
  "UPLOAD_DRIVER_LICENSE_IMAGE_INITIATED";
export const DRIVER_LICENSE_IMAGE_UPLOADED = "DRIVER_LICENSE_IMAGE_UPLOADED";

export const OWNERSHIP_CERTIFICATE_IMAGE_ADDED =
  "OWNERSHIP_CERTIFICATE_IMAGE_ADDED";
export const OWNERSHIP_CERTIFICATE_IMAGE_DELETED =
  "OWNERSHIP_CERTIFICATE_IMAGE_DELETED";
export const UPLOAD_OWNERSHIP_CERTIFICATE_IMAGE_INITIATED =
  "UPLOAD_OWNERSHIP_CERTIFICATE_IMAGE_INITIATED";
export const OWNERSHIP_CERTIFICATE_IMAGE_UPLOADED =
  "OWNERSHIP_CERTIFICATE_IMAGE_UPLOADED";

export const VEHICLE_FRONT_VIEW_IMAGE_ADDED = "VEHICLE_FRONT_VIEW_IMAGE_ADDED";
export const VEHICLE_FRONT_VIEW_IMAGE_DELETED =
  "VEHICLE_FRONT_VIEW_IMAGE_DELETED";

export const VEHICLE_BACK_VIEW_IMAGE_ADDED = "VEHICLE_BACK_VIEW_IMAGE_ADDED";
export const VEHICLE_BACK_VIEW_IMAGE_DELETED =
  "VEHICLE_BACK_VIEW_IMAGE_DELETED";

export const UPLOAD_VEHICLE_IMAGE_INITIATED = "UPLOAD_VEHICLE_IMAGE_INITIATED";
export const VEHICLE_IMAGE_UPLOADED = "VEHICLE_IMAGE_UPLOADED";

export const RESET = "RESET";
