export const DRIVER_FULLNAME_ADDED = "DRIVER_FULLNAME_ADDED";
export const DRIVER_GENDER_ADDED = "DRIVER_GENDER_ADDED";
export const DRIVER_COUNTRY_ADDED = "DRIVER_COUNTRY_ADDED";

export const PHONE_ADDED = "DRIVER_PHONE_ADDED";
export const PHONE_SUBMITTED = "DRIVER_PHONE_SUBMITTED";

export const OTP_ADDED = "DRIVER_OTP_ADDED";

export const STEP_CHANGED = "DRIVER_STEP_CHANGED";

export const TERMS_CHANGED = "DRIVER_TERMS_CHANGED";
export const FIRST_FORM_VALIDATED = "FIRST_FORM_VALIDATED";

export const OTP_SENT = "DRIVER_OTP_SENT";
export const OTP_SUBMITTED = "DRIVER_OTP_SUBMITTED";
export const DRIVER_OTP_VALIDATED = "DRIVER_OTP_VALIDATED";

export const OTP_RESENT = "DRIVER_OTP_RESENT";
export const LOADING_UPDATED = "DRIVER_LOADING_UPDATED";

export const VEHICLE_CHANGED = "DRIVER_VEHICLE_CHANGED";

export const INITIATE_SUBMIT_DRIVER_FORM = "INITIATE_SUBMIT_DRIVER_FORM";
export const DRIVER_FORM_SUBMITTED = "DRIVER_FORM_SUBMITTED";

export const RESET = "RESET";
