export const FULL_NAME_ADDED = "FULL_NAME_ADDED";
export const EMAIL_ADDED = "EMAIL_ADDED";
export const SUBJECT_ADDED = "SUBJECT_ADDED";
export const MESSAGE_ADDED = "MESSAGE_ADDED";
export const FORM_SUBMITTED = "FORM_SUBMITTED";

export const INPUT_VERIFICATION = "INPUT_VERIFICATION";

export const RESET_CONTACT_US = "RESET_CONTACT_US";