export const PHONE_SUBMITTED = "PHONE_SUBMITTED";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_SIGNED_UP = "USER_SIGNED_UP";

export const PHONE_ADDED = "USER_PHONE_ADDED";
export const OTP_ADDED = "OTP_ADDED";

export const OTP_SENT = "OTP_SENT";
export const OTP_SUBMITTED = "USER_OTP_SUBMITTED";

export const USER_LOG_IN_VERIFIED = "USER_LOG_IN_VERIFIED";

export const FIRST_NAME_ADDED = "FIRST_NAME_ADDED";
export const LAST_NAME_ADDED = "LAST_NAME_ADDED";
export const EMAIL_ADDED = "EMAIL_ADDED";

export const TERMS_CHANGED = "TERMS_CHANGED";

export const USERISVALIDATED = "USERISVALIDATED";

export const RESET = "RESET";

export const LOADING_UPDATED = "LOADING_UPDATED";
export const KEEP_ME_SIGNED_IN_CHANGED = "KEEP_ME_SIGNED_IN_CHANGED";
export const STEP_CHANGED = "STEP_CHANGED";
export const GENDER_CHANGED = "GENDER_CHANGED";

export const ACCESS_TOKEN_GENERATED = "ACCESS_TOKEN_GENERATED";




export const DEVICE_TOKEN_ADDED = "DEVICE_TOKEN_ADDED";

export const OTP_RESENT = "OTP_RESENT";
